# Generated by Django 5.2 on 2025-04-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
    ]
