# Generated by Django 5.2 on 2025-04-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_board_is_public_board_content_type_board_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='board',
            name='file',
        ),
        migrations.RemoveField(
            model_name='board',
            name='visibility',
        ),
        migrations.AddField(
            model_name='board',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('content_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.board')),
            ],
        ),
    ]
