# Generated by Django 5.2 on 2025-04-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_content_board_boardcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='boardcontent',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='core.board'),
        ),
        migrations.AlterField(
            model_name='content',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.board'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'Document')], max_length=50),
        ),
    ]
