# Generated by Django 5.2 on 2025-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_content_file_boardcomment_boardlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'Document'), ('video', 'Video'), ('other', 'Other')], max_length=50),
        ),
    ]
