# Generated by Django 5.2 on 2025-04-26 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_board_slug_content_description_content_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
